services:
  - type: web
    name: olympic-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
